#!/usr/bin/julia

using Baozi

const git_url = "git@github.com:Roger-luo/Baozi.jl.git"


if length(ARGS)==0||ARGS[1]=="help"
    print("""
        \e[1;39mBaozi --A static site generator in pure Julia\e[0m

        Baozi supports LaTeX by mathjax, and slides by revealjs
        \e[1;39m===========\e[0m
        Options:

        generate: generate slides
        *\e[1;33m new\e[0m: use `new xxx` to create new files
        *\e[1;33m publish\e[0m: publish slide to origin master
        *\e[1;33m publish=gh-pages\e[0m: publish slide to origin gh-pages
        *\e[1;33m init\e[0m : init a directory\n
        """)
else
    i=1
    while i ≤ length(ARGS)
        if ARGS[i] == "generate"
            # try 
                gen(readstring(".working_dir"));i+=1;
            # catch
            #     error("july do not exist\n")
            # end
        elseif ARGS[i] == "new"
            
            cp("templates/slide.md","_slides/$(ARGS[i+1]).md")
            i += 2
        elseif "publish"==ARGS[i]
            run(`git push origin master`);i+=1;
        elseif "publish=gh-pages"==ARGS[i]
            try 
                run(`git checkout -b gh-pages`)
            catch
                run(`git checkout gh-pages`)
            end
            run(`git push origin gh-pages`);i+=1;
            run(`git checkout master`)
        elseif "init"==ARGS[i]
            try 
                mkdir("$(ARGS[i+1])")
            catch
                error("dir exists!\n")
            end
            cd("$(ARGS[i+1])");i+=2;
            init(pwd())
            write(".working_dir","$(pwd())")
            isdefined(:git_url)?run(`git remote add origin $git_url`):nothing
        else
            error("Do not have this command\n")
        end
    end
end